### ISSUE TITLE
 Warning: a promise was created in a handler at /node_modules/graphql-jit/src/execution.ts:789:31 but was not returned from it

### ISSUE THREAD

**Issue by wesselvdv** [ruiaraujo/graphql-jit#23]
Using Bluebird als the global promise is giving me the following error:

 Warning: a promise was created in a handler at /app/node_modules/graphql-jit/src/execution.ts:789:31 but was not returned from it

Seems that if you know what you're doing (I guess you are, ;-)), you should explicitly return null instead of undefined.

**Comment by ruiaraujo** [comment]
I will need to check what it means in detail but it should be fine to change it.
